using System.Text.Json.Serialization;

namespace EvoPaymentSDK.Enuns;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum IndentificationType
{
    ALIEN_REGISTRATION_NUMBER,
    BUSINESS_TAX_ID,
    COMPANY_REGISTRATION_NUMBER,
    CUSTOMER_IDENTIFICATION,
    DATE_OF_BIRTH,
    DRIVERS_LICENSE,
    EMAIL,
    GOVERNMENT_ISSUED,
    INDIVIDUAL_TAX_ID,
    LAW_ENFORCEMENT_IDENTIFICATION,
    MILITARY_IDENTIFICATION,
    NATIONAL_IDENTIFICATION_CARD,
    OTHER,
    PASSPORT,
    PHONE_NUMBER,
    PROXY_IDENTIFICATION,
    SOCIAL_SECURITY_NUMBER,
    TRAVEL_IDENTIFICATION,
}